language: python
python: 
  - "3.5"
  - "3.6"
  - "3.6.5"
  - "3.6.7"

install:
  - pip install -U pip
  - pip install pytest pytest-cov codecov

script: 
  - pytest --cov-config .coveragerc --cov=. tests.py
  - codecov --token=$CODECOV_TOKEN
